openapi: 3.0.3
info:
  title: Exastro Platform API (System Management)
  description: Exastro Platform API for System Manager
  version: 1.3.0
servers:
  - url: 'https://{host}'
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: 'http://{host}'
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: '{protocol}://{host}:{port}'
    description: API endpoint (Development)
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      host:
        default: localhost
      port:
        default: '30081'
tags:
  - name: TokenService
    description: tokenに関する操作
  - name: OrganizationService
    description: オーガナイゼーションに関する操作
  - name: PlanService
    description: プランに関する操作
  - name: UsageService
    description: リソース使用量に関する操作
paths:
  /auth/realms/master/protocol/openid-connect/token:
    post:
      tags:
        - TokenService
      summary: create token for system manager
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/tokenRequestBody'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponseOK'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponseError'
  /api/platform/users/_current/refresh_tokens:
    get:
      tags:
        - TokenService
      summary: List returns refresh token for system manager
      x-openapi-router-controller: controllers.token_service_controller
      operationId: refresh_token_list_for_mng
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/responseOk'
                  - $ref: '#/components/schemas/tokenRefreshList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
    delete:
      tags:
        - TokenService
      summary: delete refresh token for system manager
      x-openapi-router-controller: controllers.token_service_controller
      operationId: refresh_token_delete_for_mng
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/responseOk'
                  - type: object
                    properties:
                      data:
                        type: object
                        example: null
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/platform/organizations:
    get:
      tags:
        - OrganizationService
      summary: List returns list of organization
      x-openapi-router-controller: controllers.organization_service_controller
      operationId: organization_list
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/responseOk'
                  - $ref: '#/components/schemas/organizationList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
    post:
      tags:
        - OrganizationService
      summary: Create creates an organization
      x-openapi-router-controller: controllers.organization_service_controller
      operationId: organization_create
      parameters:
        - name: retry
          in: query
          schema:
            type: string
            description: \"1\" is retry organization create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/organizationCreate'
        required: true
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseOk'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  '/api/platform/{organization_id}/plans':
    get:
      tags:
        - PlanService
      summary: Get plan of the organization
      x-openapi-router-controller: controllers.plan_service_controller
      operationId: organization_plan_get
      parameters:
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/responseOk'
                  - $ref: '#/components/schemas/planMappingOrganizationList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
    post:
      tags:
        - PlanService
      summary: Set plan to the organization
      x-openapi-router-controller: controllers.plan_service_controller
      operationId: organization_plan_create
      parameters:
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/planMappingOrganization'
        required: true
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseOk'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  '/api/platform/{organization_id}/plans/{plan_start_datetime}':
    delete:
      tags:
        - PlanService
      summary: Delete plan to the organization
      x-openapi-router-controller: controllers.plan_service_controller
      operationId: organization_plan_delete
      parameters:
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
        - name: plan_start_datetime
          in: path
          required: true
          schema:
            type: string
            example: '2022-12-01 00:00:00'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseOk'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/platform/plans:
    get:
      tags:
        - PlanService
      summary: List returns list of plans
      x-openapi-router-controller: controllers.plan_service_controller
      operationId: plan_list
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/responseOk'
                  - $ref: '#/components/schemas/planList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
    post:
      tags:
        - PlanService
      summary: Create creates an plan
      x-openapi-router-controller: controllers.plan_service_controller
      operationId: plan_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/plan'
        required: true
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseOk'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/platform/plan_items:
    get:
      tags:
        - PlanService
      summary: List returns list of plan items
      x-openapi-router-controller: controllers.plan_service_controller
      operationId: plan_item_list
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/responseOk'
                  - $ref: '#/components/schemas/planItemList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/platform/usages:
    get:
      tags:
        - UsageService
      summary: List returns list of usage
      x-openapi-router-controller: controllers.usage_service_controller
      operationId: usage_list
      parameters:
        - name: organization_id
          in: query
          schema:
            type: string
        - name: id
          in: query
          description: filter id. (prefix match)
          schema:
            type: string
            example: platform.workspaces
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/responseOk'
                  - $ref: '#/components/schemas/usageOrganizationList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
components:
  schemas:
    responseOk:
      title: A successful base response.
      type: object
      properties:
        result:
          type: integer
          example: 200
        message:
          type: string
          example: SUCCESS
        ts:
          type: string
          format: date-time
    responseStat:
      type: object
      properties:
        create_timestamp:
          type: string
          format: date-time
        create_user:
          type: string
        last_update_timestamp:
          type: string
          format: date-time
        last_update_user:
          type: string
    runtimeError:
      type: object
      properties:
        result:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: Error Message
        ts:
          type: string
          format: date-time
        data:
          type: object
          example: null
    organization:
      title: organization is a definition of Organization resource.
      type: object
      properties:
        id:
          type: string
          example: org1
        name:
          type: string
          example: name of org1
        organization_managers:
          type: array
          items:
            $ref: '#/components/schemas/usernameOnly'
        active_plan:
          type: object
          properties:
            id:
              type: string
              example: plan-1
        plans:
          type: array
          items:
            $ref: '#/components/schemas/planMappingOrganization'
    organizationCreate:
      title: organization is a definition of Organization resource.
      type: object
      properties:
        id:
          type: string
          example: org1
        name:
          type: string
          example: organization of org1
        organization_managers:
          type: array
          items:
            $ref: '#/components/schemas/organizationUserCreate'
        plan:
          type: object
          properties:
            id:
              type: string
              example: plan-1
        options:
          type: object
          description: Organization Add Json Parameter (json of KeyCloak)
      required:
        - id
    organizationUserCreate:
      title: organization-user is a definition of User resource.
      type: object
      properties:
        username:
          type: string
          example: user-id
        email:
          type: string
          example: user e-mail address
        firstName:
          type: string
        lastName:
          type: string
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/userCredentials'
        requiredActions:
          $ref: '#/components/schemas/userRequiredActions'
        enabled:
          type: boolean
      required:
        - username
    organizationList:
      title: roleList is list of Role resources.
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/organization'
    organizationSetting:
      title: organizationSetting is a definition of oraganaization setting resource.
      type: object
      properties:
        token:
          type: object
          properties:
            refresh_token_max_lifespan_enabled:
              type: boolean
              example: true
            refresh_token_max_lifespan_days:
              type: integer
              example: 365
              maximum: 1095
              minimum: 1
            access_token_lifespan_minutes:
              type: integer
              example: 1440
              maximum: 10080
              minimum: 1
    planMappingOrganization:
      type: object
      required:
        - id
        - start_datetime
      properties:
        id:
          type: string
          example: plan-1
        start_datetime:
          type: string
          example: '2022-12-01 00:00:00'
    planMappingOrganizationList:
      title: plan item list is list of plan items resources.
      type: object
      properties:
        data:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/planMappingOrganization'
              - $ref: '#/components/schemas/responseStat'
    plan:
      title: plan is a definition of Plan resource.
      type: object
      properties:
        id:
          type: string
          example: plan-1
        name:
          type: string
          example: name of plan
        informations:
          type: object
          properties:
            description:
              type: string
        limits:
          type: object
          properties:
            limit.id:
              type: number
          example:
            platform.workspaces: 100
            platform.roles: 200
    planList:
      title: planList is list of Plan resources.
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/plan'
    planItem:
      title: planItem is a definition of plan item resource.
      type: object
      properties:
        id:
          type: string
          example: platform.workspaces
        informations:
          type: object
          properties:
            description:
              type: string
    planItemList:
      title: plan item list is list of plan items resources.
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/planItem'
    limits:
      title: limitValue is a definition of Limit Value resource.
      type: object
      properties:
        data:
          type: object
          properties:
            limit.id:
              type: number
          example:
            platform.workspaces: 100
            platform.roles: 200
    limitsList:
      title: limitValue is a definition of Limit Value resource.
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              organization_id:
                type: string
                example: organization_id
              limits:
                type: object
                properties:
                  limit.id:
                    type: number
                example:
                  platform.workspaces: 100
                  platform.roles: 200
    usage:
      title: usage is a definition of current value resource.
      type: object
      properties:
        id:
          type: string
          example: platform.workspaces
        current_value:
          type: number
          example: 100
    usageList:
      title: usageList is list of usage resources.
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/usage'
          example:
            - id: platform.workspaces
              current_value: 100
            - id: platform.users
              current_value: 200
            - id: platform.roles
              current_value: 300
    usageOrganizationList:
      title: usageList is list of usage resources.
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              organization_id:
                type: string
              usages:
                type: array
                items:
                  $ref: '#/components/schemas/usage'
          example:
            - organization_id: organization_1
              usages:
                - id: platform.workspaces
                  current_value: 101
                - id: platform.users
                  current_value: 102
                - id: platform.roles
                  current_value: 103
            - organization_id: organization_2
              usages:
                - id: platform.workspaces
                  current_value: 201
                - id: platform.users
                  current_value: 202
                - id: platform.roles
                  current_value: 203
    role:
      title: role is a definition of Role resource.
      type: object
      properties:
        name:
          type: string
          example: role-1
    roleList:
      title: roleList is list of Role resources.
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/role'
    usernameOnly:
      title: username of User resource.
      type: object
      properties:
        username:
          type: string
    user:
      title: user is a definition of User resource.
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: firstname lastname
        firstName:
          type: string
        lastName:
          type: string
        preferred_username:
          type: string
        enabled:
          type: boolean
        create_timestamp:
          type: string
          format: date-time
    userList:
      title: userList is list of User resources.
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/user'
    userCreate:
      title: user is a definition of User resource.
      type: object
      properties:
        username:
          type: string
          example: user-id
        password:
          type: string
          example: password
        password_temporary:
          type: boolean
          default: true
        email:
          type: string
          example: user e-mail address
        firstName:
          type: string
        lastName:
          type: string
        enabled:
          type: boolean
          default: true
      required:
        - username
        - password
    userCredentials:
      title: userCredentials is Credentials of User resources.
      type: object
      properties:
        type:
          type: string
          example: password
        value:
          type: string
          example: password
        temporary:
          type: boolean
          example: true
    userRequiredActions:
      title: userRequiredActions is RequiredActions of User resources.
      type: array
      items:
        type: string
        example: UPDATE_PROFILE
        description: \"UPDATE_PROFILE\" or \"UPDATE_PASSWORD\" or \"VERIFY EMAIL\" or \"UPDATE USER LOCAL\" or \"CONFIGURE OTP\"
    member:
      title: member is a definition of Member resource.
      type: object
      properties:
        name:
          type: string
          example: firstname lastname
        firstName:
          type: string
        lastName:
          type: string
    memberList:
      title: memberList is list of Member resources.
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/member'
    workspace:
      title: workspace is a definition of Workspace resource.
      type: object
      properties:
        id:
          type: string
          example: workspace-1
        name:
          type: string
          example: name of workspace
        informations:
          type: object
          properties:
            description:
              type: string
            environments:
              type: array
              items:
                $ref: '#/components/schemas/environment'
            workspace_administrators:
              type: array
              items:
                $ref: '#/components/schemas/workspace_administrator'
    workspaceList:
      title: workspaceList is list of Workspace resources.
      type: object
      properties:
        data:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/workspace'
              - $ref: '#/components/schemas/responseStat'
    userWorkspace:
      title: workspace is a definition of Workspace resource.
      type: object
      properties:
        id:
          type: string
          example: workspace-1
        name:
          type: string
          example: name of workspace
        create_timestamp:
          type: string
          format: date-time
        last_update_timestamp:
          type: string
          format: date-time
    userWorkspaceList:
      title: WorkspaceList is a list of workspace resources that users can access.
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/userWorkspace'
    environment:
      title: environments is a definition of Workspace information resource.
      type: object
      properties:
        name:
          type: string
          example: staging
    workspace_administrator:
      title: workspace_administrator is a definition of Workspace information resource.
      type: object
      properties:
        id:
          type: string
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    roleDetailList:
      title: WorkspaceList is a list of workspace resources that users can access.
      type: object
      properties:
        data:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/roleDetailWorkspace'
              - $ref: '#/components/schemas/roleDetailOrganization'
    roleDetailOrganization:
      title: role is a definition of Role resource.
      type: object
      properties:
        name:
          type: string
          example: organization-role-1
        description:
          type: string
          example: role description
        kind:
          type: string
          example: organization
        authorities:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: _og-upd
    roleDetailWorkspace:
      title: role is a definition of Role resource.
      type: object
      properties:
        name:
          type: string
          example: role-1
        description:
          type: string
          example: role description
        kind:
          type: string
          example: workspace
        authorities:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
            example:
              - name: _workspace-1-admin
              - name: workspace-1
        workspaces:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: workspace-1
    roleDetailWorkspacePut:
      title: role is a definition of Role resource.
      type: object
      properties:
        description:
          type: string
          example: role description
        kind:
          type: string
          example: workspace
        workspaces:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: workspace-1
    roleMappingUser:
      title: userList is list of User resources.
      type: array
      items:
        $ref: '#/components/schemas/roleUser'
      example:
        - preferred_username: username-1
        - preferred_username: username-2
        - preferred_username: username-3
    roleUser:
      title: role mapping user is a definition of User resource.
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: firstname lastname
        firstName:
          type: string
        lastName:
          type: string
        preferred_username:
          type: string
        enabled:
          type: boolean
        create_timestamp:
          type: string
          format: date-time
    tokenRequestBody:
      title: create refresh token request parameter.
      type: object
      properties:
        client_id:
          type: string
          example: '_{organization_id}-api'
        grant_type:
          type: string
          description: '"password" or "refresh_token"'
        scope:
          type: string
          example: openid offline_access
          description: Specified when grant_type = "password"
        username:
          type: string
          description: Specified when grant_type = "password"
        password:
          type: string
          example: password
          description: Specified when grant_type = "password"
        totp:
          type: string
          example: 123456
          description: one time password. Specified when grant_type = "password" and two-fatctor-authnication
        refresh_token:
          type: string
          description: Specified when grant_type = "refresh_token"
    tokenResponseOK:
      title: A successful create token.
      type: object
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
        refresh_token:
          type: string
        id_token:
          type: string
        not-before-policy:
          type: integer
        session_state:
          type: string
          format: uuid
        scope:
          type: string
          example: openid profile offline_access email
    tokenResponseError:
      title: A successful create token.
      type: object
      properties:
        error:
          type: string
          example: invalid_grant
        error_description:
          type: string
          example: Invalid user credentials
    tokenRefreshList:
      title: roleList is list of Role resources.
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
              start_timestamp:
                type: string
                format: date-time
              lastaccess_timestamp:
                type: string
                format: date-time
              expire_timestamp:
                type: string
                format: date-time
  securitySchemes:
    BearerAuth:
      description: Credentials or access token for API
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      description: Value converted from ID/Password in base64
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
security:
  - BearerAuth: []
  - BasicAuth: []
